name: story_designer

description: A package for creating instagram like story, you can use this package to edit images and make it story ready by adding other contents over it like text.

version: 0.1.0

homepage: https://github.com/mrgulshanyadav/story_designer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  gallery_saver: ^2.3.2
  google_fonts: ^2.3.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
